
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "chef-ws"
  config.vm.network "private_network", ip: "192.168.10.11"
  config.vm.network "forwarded_port", guest: 22, host: 2211, auto_correct: true
  config.vm.define "chef-ws" do |chefws|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "chef-ws"
    vb.memory = 256
    vb.cpus = 2
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/var/sync"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
  config.vm.provision "shell", inline: " echo >> /home/vagrant/.ssh/authorized_keys; cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", privileged: false
  
  config.vm.provision "shell", inline: <<-SHELL
    yum -y update
    yum -y install git
    useradd -G wheel -m rajkipa
    echo 'passwd123' |passwd --stdin rajkipa
  SHELL

  config.vm.provision "file", source: "../chef-server/test-validator.pem", destination: "/tmp/test-validator.pem"
  config.vm.provision "file", source: "../chef-server/rajkipa.pem", destination: "/tmp/rajkipa.pem"
  config.vm.provision "shell", inline: <<-EOF
    sed -i.bkp '/^PasswordAuthentication/ s/no[ \t  ]*$/yes/' /etc/ssh/sshd_config
    systemctl restart sshd
    echo '192.168.10.10   chef-server.test.raj    chef-server' >> /etc/hosts
    cd /home/rajkipa
    [[ ! -d .ssh  ]] && mkdir .ssh
    chmod 700 .ssh
    echo >> .ssh/authorized_keys
    cat /tmp/id_rsa.pub >> .ssh/authorized_keys
    curl -L https://www.opscode.com/chef/install.sh | bash
    [[ ! -d .chef  ]] && mkdir .chef
    cp /tmp/test-validator.pem .chef/test-validator.pem
    cp /tmp/rajkipa.pem .chef/rajkipa.pem
    cp /var/sync/knife.rb /home/rajkipa/.chef/knife.rb
    chown -R rajkipa:rajkipa /home/rajkipa
    echo 'rajkipa  ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
#    rm -f /tmp/*.pem /tmp/id_rsa.pub
  EOF


end
