
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "chef-server"
  config.vm.network "private_network", ip: "192.168.10.11"
  config.vm.network "forwarded_port", guest: 22, host: 2211, auto_correct: true
  config.vm.define "chef-server" do |chefserver|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "chef-server"
    vb.memory = 1536
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off" ]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off" ]
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/var/sync"
  config.vm.synced_folder "../data", "/data"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
  config.vm.provision "shell", inline: " echo >> /home/vagrant/.ssh/authorized_keys; cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", privileged: false

  config.vm.provision "file", source: "~/packages/chefpkgs/chef-server-core-12.8.0-1.el7.x86_64.rpm", destination: "/tmp/chef-server-core-12.8.0-1.el7.x86_64.rpm"
  config.vm.provision "shell", inline: <<-SHELL
    rm -f /var/sync/*.pem
    sed -i.bkp '/^PasswordAuthentication/ s/no[ \t ]*$/yes/' /etc/ssh/sshd_config
    systemctl restart sshd
    yum -y update
    rpm -ivh  /tmp/chef-server-core-12.8.0-1.el7.x86_64.rpm
    rm -f /tmp/chef-server-core-12.8.0-1.el7.x86_64.rpm
    chef-server-ctl reconfigure
    chef-server-ctl install chef-manage
    chef-server-ctl install opscode-reporting
    chef-server-ctl reconfigure 
    chef-manage-ctl reconfigure --accept-license
    opscode-reporting-ctl reconfigure --accept-license
    chef-server-ctl user-create rajkipa 'Raj Kishore' 'Panigrahi' rajkipa@test.com 'passwd123' --filename /var/sync/rajkipa.pem
    chef-server-ctl org-create test 'test' --association_user rajkipa --filename /var/sync/test-validator.pem
    rm -f /tmp/id_rsa.pub
  SHELL

end
