
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "client1.example.com"
  config.vm.network "private_network", ip: "192.168.10.21"
  config.vm.network "forwarded_port", guest: 22, host: 2221, auto_correct: true
  config.vm.define "client1" do |c1|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "client1"
    vb.memory = 512
    vb.cpus = 2
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/home/vagrant/sync"
  config.vm.synced_folder "../data", "/data"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
  config.vm.provision "shell", inline: " echo >> /home/vagrant/.ssh/authorized_keys; cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", privileged: false
  
#  config.vm.provision "shell", inline: <<-SHELL
#    yum -y update
#    yum -y install git
#    useradd -m rajkipa
#    echo 'passwd123' |passwd --stdin rajkipa
#  SHELL

#  config.vm.provision "shell", inline: <<-EOF
#    cd /home/rajkipa
#    [[ ! -d .ssh  ]] && mkdir .ssh
#    chmod 700 .ssh
#    echo >> .ssh/authorized_keys
#    cat /tmp/id_rsa.pub >> .ssh/authorized_keys
#    chown -R rajkipa:rajkipa /home/rajkipa
#    echo 'rajkipa  ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
#    rm -f /tmp/*.pem /tmp/id_rsa.pub
#  EOF

  config.vm.provision "chef_client" do |chef|
    chef.chef_server_url = "https://192.168.10.11/organizations/test/"
    chef.validation_client_name = "test-validator"
    chef.validation_key_path = "../chef-server/test-validator.pem"
    chef.provisioning_path = "/etc/chef"
    chef.delete_node = true
    chef.delete_client = true
  end

end
