
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "ansible"
  config.vm.network "private_network", ip: "192.168.10.14"
  config.vm.network "forwarded_port", guest: 22, host: 2214, auto_correct: true
  config.vm.define "ansible" do |ansibl|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible"
    vb.memory = 1536
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off" ]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off" ]
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/var/sync"
  config.vm.synced_folder "../data", "/data"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
  config.vm.provision "shell", inline: " echo >> /home/vagrant/.ssh/authorized_keys; cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", privileged: false

  config.vm.provision "shell", inline: <<-SHELL
    rm -f /var/sync/*.pem
    sed -i.bkp '/^PasswordAuthentication/ s/no[ \t ]*$/yes/' /etc/ssh/sshd_config
    systemctl restart sshd
    yum -y update
    yum -y install wget
    cd /tmp
    wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
    rpm -ivh epel-release-7-8.noarch.rpm
    yum -y install ansible
  SHELL

end
